name: Python Workflow

on:
    push:
        branches:
            - main
    pull_request:

jobs:
  run-python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{secrets.DOCKER_PASSORD}}" | docker login -u "${{secrets.DOCKER_USERNAME}}" --password-stdin

      - name: Build the docker image
        run: |
            docker build -t ${{ secrets.DOCKER_USERNAME }}/test-action-image:latest .

      - name: Push the Docker image
        run: |
            docker push ${{ secrets.DOCKER_USERNAME }}/test-action-image:latest



