name: Python Workflow

on:
    push:
        branches:
            - main
    pull_request:

jobs:
  run-python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
            python-version: 3.9


      - name: Run Python Script
        run: python main.py



